### Disaster Messages dataset
This dataset conians about 26K service requests from different parts of the world after a disaster (floods, earthquaks, etc)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("/Users/dianaemal/Downloads/archive-3/disaster_messages.csv")
df.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [5]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26248 entries, 0 to 26247
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26248 non-null  int64
 1   message   26248 non-null  object
 2   original  10184 non-null  object
 3   genre     26248 non-null  object
dtypes: int64(1), object(3)
memory usage: 820.4+ KB

In [6]:
df.nunique()

id          26180
message     26177
original     9630
genre           3
dtype: int64

In [10]:
pd.set_option('display.max_colwidth', None)
print(df["message"].head(10))

0                                                        Weather update - a cold front from Cuba that could pass over Haiti
1                                                                                   Is the Hurricane over or is it not over
2                                                                                           Looking for someone but no name
3                      UN reports Leogane 80-90 destroyed. Only Hospital St. Croix functioning. Needs supplies desperately.
4                                                           says: west side of Haiti, rest of the country today and tonight
5                                                                                    Information about the National Palace-
6                                                                                            Storm at sacred heart of jesus
7                                                               Please, we need tents and water. We are in Silo, Thank you!
8                                                                           I would like to receive the messages, thank you
9    I am in Croix-des-Bouquets. We have health issues. They ( workers ) are in Santo 15. ( an area in Croix-des-Bouquets )
Name: message, dtype: object

### US Consumer Complaints (CFPB Dataset)

In [13]:
df2 = pd.read_csv("/Users/dianaemal/Downloads/archive-4/complaints-2025-11-11_23_26.csv")

In [15]:
df2.shape
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372815 entries, 0 to 1372814
Data columns (total 18 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   Date received                 1372815 non-null  object
 1   Product                       1372815 non-null  object
 2   Sub-product                   1353725 non-null  object
 3   Issue                         1372815 non-null  object
 4   Sub-issue                     1249332 non-null  object
 5   Consumer complaint narrative  1372814 non-null  object
 6   Company public response       759977 non-null   object
 7   Company                       1372814 non-null  object
 8   State                         1368074 non-null  object
 9   ZIP code                      1372814 non-null  object
 10  Tags                          136415 non-null   object
 11  Consumer consent provided?    1372814 non-null  object
 12  Submitted via                 1372814 non-null  object
 13  Date sent to company          1372814 non-null  object
 14  Company response to consumer  1372810 non-null  object
 15  Timely response?              1372814 non-null  object
 16  Consumer disputed?            61750 non-null    object
 17  Complaint ID                  1372814 non-null  float64
dtypes: float64(1), object(17)
memory usage: 188.5+ MB

In [20]:
df2["Consumer complaint narrative"].head(1)

0    In accordance with the Fair Credit Reporting Act, Everything has to be 100 % accurate on my credit report.\n\nThe credit burruea stated my account was properly investigated, but how is that possible If the open date isn't accurute The date last active isnt accurate. And the date last reported is inaccurate. That is grounds for removal.\n\nThey violated my rights under the 15 U.S.C. 1681, Section 602 A states I have right to privacy.\n\n15 U.S.C 1681 Section 604 also states that Consumer report agencies can not furnish my account without my permission.\n\nThey also violated my Hippa rights. \nI had no knowledge or consent of my medical info being disclosed.
Name: Consumer complaint narrative, dtype: object

### Hotel review dataset

In [21]:
df3 = pd.read_csv("/Users/dianaemal/Downloads/archive-4/Hotel_Reviews.csv")

In [23]:
df3.head(2)

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available via all possible sites i use when planing my trips so no one will make the mistake of booking this place I made my booking via booking com We stayed for 6 nights in this hotel from 11 to 17 July Upon arrival we were placed in a small room on the 2nd floor of the hotel It turned out that this was not the room we booked I had specially reserved the 2 level duplex room so that we would have a big windows and high ceilings The room itself was ok if you don t mind the broken window that can not be closed hello rain and a mini fridge that contained some sort of a bio weapon at least i guessed so by the smell of it I intimately asked to change the room and after explaining 2 times that i booked a duplex btw it costs the same as a simple double but got way more volume due to the high ceiling was offered a room but only the next day SO i had to check out the next day before 11 o clock in order to get the room i waned to Not the best way to begin your holiday So we had to wait till 13 00 in order to check in my new room what a wonderful waist of my time The room 023 i got was just as i wanted to peaceful internal garden view big window We were tired from waiting the room so we placed our belongings and rushed to the city In the evening it turned out that there was a constant noise in the room i guess it was made by vibrating vent tubes or something it was constant and annoying as hell AND it did not stop even at 2 am making it hard to fall asleep for me and my wife I have an audio recording that i can not attach here but if you want i can send it via e mail The next day the technician came but was not able to determine the cause of the disturbing sound so i was offered to change the room once again the hotel was fully booked and they had only 1 room left the one that was smaller but seems newer,397,1403,Only the park outside of the hotel was beautiful,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 6 nights ']",0 days,52.360576,4.915968
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great location surroundings rooms amenities and service Two recommendations however firstly the staff upon check in are very confusing regarding deposit payments and the staff offer you upon checkout to refund your original payment and you can make a new one Bit confusing Secondly the on site restaurant is a bit lacking very well thought out and excellent quality food for anyone of a vegetarian or vegan background but even a wrap or toasted sandwich option would be great Aside from those minor minor things fantastic spot and will be back when i return to Amsterdam,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 4 nights ']",0 days,52.360576,4.915968

In [24]:
df3.shape
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515738 entries, 0 to 515737
Data columns (total 17 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   Hotel_Address                               515738 non-null  object
 1   Additional_Number_of_Scoring                515738 non-null  int64
 2   Review_Date                                 515738 non-null  object
 3   Average_Score                               515738 non-null  float64
 4   Hotel_Name                                  515738 non-null  object
 5   Reviewer_Nationality                        515738 non-null  object
 6   Negative_Review                             515738 non-null  object
 7   Review_Total_Negative_Word_Counts           515738 non-null  int64
 8   Total_Number_of_Reviews                     515738 non-null  int64
 9   Positive_Review                             515738 non-null  object
 10  Review_Total_Positive_Word_Counts           515738 non-null  int64
 11  Total_Number_of_Reviews_Reviewer_Has_Given  515738 non-null  int64
 12  Reviewer_Score                              515738 non-null  float64
 13  Tags                                        515738 non-null  object
 14  days_since_review                           515738 non-null  object
 15  lat                                         512470 non-null  float64
 16  lng                                         512470 non-null  float64
dtypes: float64(4), int64(5), object(8)
memory usage: 66.9+ MB

### Twitter customer support daatset

In [25]:
df4 = pd.read_csv("/Users/dianaemal/Downloads/archive-4/sample.csv")

In [26]:
df4.head(2)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregarded and the tapped notification under the keyboard is opened😡😡😡,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,"@105835 Your business means a lot to us. Please DM your name, zip code and additional details about your concern. ^RR https://t.co/znUu1VJn9r",NaN,119239.0

In [27]:
df4.shape
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tweet_id                 93 non-null     int64
 1   author_id                93 non-null     object
 2   inbound                  93 non-null     bool
 3   created_at               93 non-null     object
 4   text                     93 non-null     object
 5   response_tweet_id        65 non-null     object
 6   in_response_to_tweet_id  68 non-null     float64
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 4.6+ KB